namespace: cxnam

deployParams:
  server:
    name: server-ooo
    replicaCount: 1
    labels:
      - labelKey: component
        labelValue: server
      - labelKey: student
        labelValue: ooo
  iothubMqtt:
    name: mqtt-ooo
    replicaCount: 1
    labels:
      - labelKey: component
        labelValue: mqtt
      - labelKey: student
        labelValue: ooo

containerParams:
  server:
    repository: ensaas
    imageName: iot-home-server
    tag: 2.0.0
    port: 3000
    resources:
      limits:
        cpu: 20m
        memory: 64Mi
        ephemeralStorage: 64Mi
      requests:
        cpu: 20m
        memory: 64Mi
  mqtt:
    repository: ensaas
    imageName: iot-home-mqtt
    tag: 2.0.0
    resources:
      limits:
        cpu: 20m
        memory: 64Mi
        ephemeralStorage: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi

svcClusterIps:
  server:
    name: server-ooo
    selectors:
      - selectorKey: component
        selectorValue: server
      - selectorKey: student
        selectorValue: ooo
    ports:
      - port: 3000
        targetPort: 3000

global:
  database:
    secretName: ooo-secret
  url:
    host: .cxnam.ews.en.internal
  ensaasApps:
    apiSso:
      internalUrl: http://api.sso.ensaas.en.internal/v4.0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: iot-home-ooo
      paths:
        - path: /?(.*)
          backend:
            serviceName: server-ooo
            servicePort: 3000
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

# nodeSelector: {}
# tolerations: []
# affinity: {}
