apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-ooo
  labels:
    name: test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: server
      student: ooo
  template:
    metadata:
      labels:
        component: server
        student: ooo
    spec:
      containers:
        - name: server
          image: bsdfuyih2gh/iot-home-server:3.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 20m
              memory: 64Mi
              ephemeral-storage: 64Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: ENSAAS_SERVICES
              valueFrom:
                secretKeyRef:
                  name: datahub-cxnam-secret
                  key: ENSAAS_SERVICES
